server:
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /poemsearch
  port: 8999
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poem?useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 192.168.174.100
    port: 7777
  data:
    elasticsearch:
      cluster-nodes: 192.168.174.100:9300
      cluster-name: elasticsearch
  application:
    name: elasticsearch
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.zpark.entity
  mapper-locations: classpath:com/zpark/mapper/*Mapper.xml
logging:
  level:
    root: info
    com.zpark.dao: debug